name: run check.js

on:
  pull_request: {}

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  checks: write

inputs:
  token:
    type: string
    description: 'The GitHub token to use for authentication'
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install dependencies
        run: npm install

      - name: run check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run check
